name: CI/CD Pipeline User Management

on:
  push:
    branches: [ "**" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1 : TESTS
  tests:
    name: 🧪 Run Unit & Integration Tests
    runs-on: ubuntu-latest
    services:
      # On lance une vraie DB pour les tests d'intégration
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: userDb
          POSTGRES_USER: appuser
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # CACHE DES DÉPENDANCES (Exigence 10pts)

      - name: Run Tests with Maven
        run: mvn clean test
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/userDb
          SPRING_DATASOURCE_USERNAME: appuser
          SPRING_DATASOURCE_PASSWORD: password
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
          SPRING_JPA_HIBERNATE_DDL_AUTO: update

  # JOB 2 & 3 : BUILD & PUSH (Séquentiel, dépend des tests)
  build-and-push:
    name:  Build and Push Docker Image
    needs: tests
    if: github.event_name != 'pull_request' # On ne push pas sur les PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/user-management-api
          tags: |
            type=sha,prefix=sha-
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # JOB 4 : DEPLOY (Simulation structurée)
  deploy:
    name: Deployment
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying version ${{ github.sha }} to Staging Environment..."
          echo "Simulating: ssh user@staging-vps 'docker compose pull && docker compose up -d'"

      - name: Deploy to Production
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "Deploying version ${{ github.ref_name }} to Production Environment..."
          echo "Executing Rollback strategy: Save current state before update."